#!/usr/bin/env python3
"""
VEX Corpus Query Interface

Ask natural language questions about VEX code and get answers from the corpus
and/or generated by Nemotron.

Usage:
    python ask.py "How do I smooth points using point clouds?"
    python ask.py --interactive
    python ask.py --search "pcopen"
"""

import asyncio
import argparse
import json
import sys
from pathlib import Path
from typing import Optional

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

sys.path.insert(0, str(Path(__file__).parent))

from ollama.src.client import OllamaClient


# ============================================================================
# Corpus Search
# ============================================================================

class CorpusSearcher:
    """Search the VEX corpus for relevant samples."""

    def __init__(self, corpus_dir: Path = None):
        self.corpus_dir = corpus_dir or Path("C:/Users/User/vex-corpus/output")
        self.samples: list[dict] = []
        self._loaded = False

    def load(self):
        """Load all corpus files."""
        if self._loaded:
            return

        for corpus_file in self.corpus_dir.glob("corpus_*.json"):
            try:
                with open(corpus_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    self.samples.extend(data.get("samples", []))
            except Exception:
                continue

        # Deduplicate by ID
        seen = set()
        unique = []
        for s in self.samples:
            if s.get("id") not in seen:
                seen.add(s.get("id"))
                unique.append(s)
        self.samples = unique

        self._loaded = True
        print(f"[CORPUS] Loaded {len(self.samples)} samples")

    def search(self, query: str, limit: int = 5) -> list[dict]:
        """Search corpus for relevant samples."""
        self.load()

        query_lower = query.lower()
        query_terms = query_lower.split()

        scored = []
        for sample in self.samples:
            score = 0

            # Check code content
            code = sample.get("code", "").lower()
            for term in query_terms:
                if term in code:
                    score += 2

            # Check classification
            classification = sample.get("classification", {})
            context = classification.get("context", "").lower()
            topic = classification.get("topic", "").lower()

            if any(term in context for term in query_terms):
                score += 3
            if any(term in topic for term in query_terms):
                score += 3

            # Check functions
            functions = classification.get("functions", [])
            for func in functions:
                if isinstance(func, dict):
                    func_name = func.get("name", "").lower()
                else:
                    func_name = str(func).lower()
                if any(term in func_name for term in query_terms):
                    score += 4

            # Check prompt if available
            generation = sample.get("generation", {})
            prompt = generation.get("prompt", "").lower()
            if any(term in prompt for term in query_terms):
                score += 2

            if score > 0:
                scored.append((score, sample))

        # Sort by score descending
        scored.sort(key=lambda x: -x[0])

        return [s for _, s in scored[:limit]]


# ============================================================================
# VEX Assistant
# ============================================================================

SYSTEM_PROMPT = """You are a VEX (Houdini's Vector Expression Language) expert assistant.

You help users write VEX code for Houdini. When answering:
1. Provide working VEX code examples
2. Explain the key functions and concepts used
3. Mention which wrangle context (point/prim/vertex/detail) the code runs in
4. Note any channel parameters (ch(), chf(), etc.) that can be adjusted

Be concise but thorough. Always include runnable code."""


class VEXAssistant:
    """Natural language interface to VEX knowledge."""

    def __init__(self):
        self.client = OllamaClient()
        self.searcher = CorpusSearcher()
        self.model = "nemotron-3-nano:latest"  # Use the smarter model for Q&A
        self.history: list[dict] = []

    async def ask(self, question: str, use_corpus: bool = True) -> str:
        """Ask a question about VEX."""

        # Search corpus for relevant examples
        context = ""
        if use_corpus:
            results = self.searcher.search(question, limit=3)
            if results:
                context = "\n\nRelevant examples from corpus:\n"
                for i, sample in enumerate(results, 1):
                    code = sample.get("code", "")
                    classification = sample.get("classification", {})
                    ctx = classification.get("context", "unknown")
                    topic = classification.get("topic", "")

                    context += f"\n--- Example {i} ({ctx} context, {topic}) ---\n"
                    context += f"```vex\n{code}\n```\n"

        # Build prompt
        prompt = question
        if context:
            prompt = f"{question}\n{context}\nBased on these examples and your knowledge, please answer the question."

        # Call Ollama
        import httpx
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "http://localhost:11434/api/generate",
                    json={
                        "model": self.model,
                        "system": SYSTEM_PROMPT,
                        "prompt": prompt,
                        "stream": False,
                        "options": {
                            "temperature": 0.7,
                            "num_predict": 2048,
                        }
                    },
                    timeout=120.0
                )
                data = response.json()
                return data.get("response", "No response generated.")

        except Exception as e:
            return f"Error: {e}"

    async def search_only(self, query: str, limit: int = 5) -> list[dict]:
        """Just search the corpus without LLM."""
        return self.searcher.search(query, limit)


# ============================================================================
# Interactive Mode
# ============================================================================

async def interactive_mode(assistant: VEXAssistant):
    """Run interactive Q&A session."""
    print("\n" + "=" * 60)
    print("  VEX CORPUS - Interactive Q&A")
    print("=" * 60)
    print("  Commands:")
    print("    /search <query>  - Search corpus only")
    print("    /corpus on|off   - Toggle corpus context")
    print("    /quit            - Exit")
    print("=" * 60 + "\n")

    use_corpus = True

    while True:
        try:
            question = input("\n[You] ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye!")
            break

        if not question:
            continue

        # Commands
        if question.startswith("/"):
            parts = question.split(maxsplit=1)
            cmd = parts[0].lower()

            if cmd == "/quit":
                print("Goodbye!")
                break

            elif cmd == "/search":
                if len(parts) > 1:
                    results = await assistant.search_only(parts[1])
                    print(f"\n[Found {len(results)} results]")
                    for i, sample in enumerate(results, 1):
                        code = sample.get("code", "")[:100]
                        ctx = sample.get("classification", {}).get("context", "?")
                        print(f"\n{i}. [{ctx}] {code}...")
                else:
                    print("Usage: /search <query>")

            elif cmd == "/corpus":
                if len(parts) > 1:
                    use_corpus = parts[1].lower() in ("on", "true", "yes", "1")
                    print(f"Corpus context: {'ON' if use_corpus else 'OFF'}")
                else:
                    print(f"Corpus context is {'ON' if use_corpus else 'OFF'}")

            else:
                print(f"Unknown command: {cmd}")

            continue

        # Regular question
        print("\n[Thinking...]")
        response = await assistant.ask(question, use_corpus=use_corpus)
        print(f"\n[VEX Assistant]\n{response}")


# ============================================================================
# Main
# ============================================================================

async def main():
    parser = argparse.ArgumentParser(
        description="Ask questions about VEX code",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python ask.py "How do I blur point positions?"
  python ask.py "What does pcopen do?"
  python ask.py --search "noise"
  python ask.py --interactive
        """
    )

    parser.add_argument('question', nargs='?', help='Question to ask')
    parser.add_argument('--interactive', '-i', action='store_true',
                       help='Interactive Q&A mode')
    parser.add_argument('--search', '-s', metavar='QUERY',
                       help='Search corpus only (no LLM)')
    parser.add_argument('--no-corpus', action='store_true',
                       help='Skip corpus search, use only LLM knowledge')

    args = parser.parse_args()

    assistant = VEXAssistant()

    if args.interactive:
        await interactive_mode(assistant)

    elif args.search:
        results = await assistant.search_only(args.search)
        print(f"\nFound {len(results)} results for '{args.search}':\n")
        for i, sample in enumerate(results, 1):
            code = sample.get("code", "")
            ctx = sample.get("classification", {}).get("context", "?")
            topic = sample.get("classification", {}).get("topic", "?")
            print(f"--- Result {i} [{ctx}, {topic}] ---")
            print(f"```vex\n{code}\n```\n")

    elif args.question:
        print(f"\n[Question] {args.question}\n")
        print("[Thinking...]\n")
        response = await assistant.ask(args.question, use_corpus=not args.no_corpus)
        print(f"[Answer]\n{response}")

    else:
        # No args - go interactive
        await interactive_mode(assistant)


if __name__ == "__main__":
    asyncio.run(main())
